#!/usr/bin/env python3
"""bundle.py — regenerate gemini_web2api.py from the gemini_web2api/ package.

The package is the single source of truth. This script concatenates its
modules (dependency order) into one standalone file with every relative
import resolved, so ``python gemini_web2api.py`` keeps working as a
copy-anywhere, zero-dependency single file.

Usage:
    python bundle.py           # regenerate gemini_web2api.py in place
    python bundle.py --check   # exit 1 if gemini_web2api.py is stale
    python bundle.py --print   # print the bundle to stdout (write nothing)

The drift check is also wired into test_suite.py (Section A) so a stale
single file fails the test battery.
"""
import argparse
import ast
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.join(HERE, "gemini_web2api")
OUT = os.path.join(HERE, "gemini_web2api.py")

# Dependency order: each module may only import from modules above it.
MODULES = [
    "config.py",
    "models.py",
    "gemini.py",
    "tools.py",
    "multimodal.py",
    "image_bridge.py",
    "server.py",
    "__main__.py",
]

HEADER = '''#!/usr/bin/env python3
"""
gemini-web2api - Gemini Web to OpenAI API proxy. (BUNDLED single-file edition)

This file is GENERATED from the gemini_web2api/ package by bundle.py.
DO NOT EDIT THIS FILE DIRECTLY - edit gemini_web2api/*.py and run:

    python bundle.py

Usage:
    python gemini_web2api.py [--port 8081] [--config config.json]

Client configuration (Cherry Studio, ChatBox, etc.):
    Base URL: http://localhost:8081/v1
    API Key: (anything or empty)
"""
'''


def _extract_version() -> str:
    """Pull __version__ out of the package __init__.py."""
    src = open(os.path.join(PKG, "__init__.py"), encoding="utf-8").read()
    try:
        tree = ast.parse(src)
        for node in tree.body:
            if isinstance(node, ast.Assign):
                for t in node.targets:
                    if isinstance(t, ast.Name) and t.id == "__version__":
                        return ast.unparse(node.value)
    except SyntaxError:
        pass
    return '"1.1.0"'


def _rewrite_module(src: str) -> str:
    """Strip relative imports from a module; aliased ones become local aliases.

    ``from .models import MODELS as _MODELS`` -> ``_MODELS = MODELS``
    ``from .config import CONFIG``            -> (dropped; CONFIG is module-level)
    ``from . import __version__``             -> (dropped; defined in the header)
    """
    tree = ast.parse(src)
    drop = set()
    inserts = {}  # lineno -> [lines to emit just before it]
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.level > 0:
            for ln in range(node.lineno, (getattr(node, "end_lineno", None) or node.lineno) + 1):
                drop.add(ln)
            # Aliased relative imports become local aliases; keep the original
            # indentation (an import inside a function body stays indented).
            indent = " " * (node.col_offset if node.col_offset else 0)
            aliases = [f"{indent}{a.asname} = {a.name}" for a in node.names if a.asname]
            if aliases:
                inserts.setdefault(node.lineno, []).extend(aliases)
    out = []
    for lineno, line in enumerate(src.splitlines(keepends=True), start=1):
        if lineno in inserts:
            for text in inserts[lineno]:
                out.append(text + "\n")
        if lineno not in drop:
            out.append(line)
    return "".join(out)


def build_bundle() -> str:
    parts = [HEADER.rstrip() + "\n\n", f"__version__ = {_extract_version()}\n\n"]
    for mod in MODULES:
        path = os.path.join(PKG, mod)
        with open(path, encoding="utf-8") as f:
            src = f.read()
        parts.append(f"\n# ══════════════════════ module: {mod} ══════════════════════\n")
        parts.append(_rewrite_module(src).rstrip() + "\n")
    return "".join(parts)


def main():
    ap = argparse.ArgumentParser(description="Regenerate gemini_web2api.py from the gemini_web2api/ package")
    ap.add_argument("--check", action="store_true", help="verify the committed single file is not stale")
    ap.add_argument("--print", action="store_true", help="print the bundle to stdout, write nothing")
    args = ap.parse_args()

    bundle = build_bundle()
    if args.print:
        sys.stdout.write(bundle)
        return
    try:
        with open(OUT, encoding="utf-8") as f:
            current = f.read()
    except OSError:
        current = None
    if args.check:
        if current == bundle:
            print(f"OK: {os.path.relpath(OUT, HERE)} is up to date with the package.")
            return
        print(f"STALE: {os.path.relpath(OUT, HERE)} differs from the gemini_web2api/ package.",
              file=sys.stderr)
        print("Run: python bundle.py   (then commit both)", file=sys.stderr)
        sys.exit(1)
    # Belt-and-suspenders: never let a broken bundle replace a good single file.
    try:
        compile(bundle, OUT, "exec")
    except SyntaxError as e:
        print(f"ERROR: generated bundle failed to compile: {e}", file=sys.stderr)
        sys.exit(1)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(bundle)
    print(f"Regenerated {os.path.relpath(OUT, HERE)} ({len(bundle.splitlines())} lines) from gemini_web2api/.")


if __name__ == "__main__":
    main()
